# File: docker-compose.yml
services:
  serversage:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: serversage # Optional: give the container a specific name
    
    env_file:
      - .env # Load environment variables from the .env file in the project root

    environment:
      # Point to the location of the secrets inside the container
      - DISCORD_BOT_TOKEN_FILE=/run/secrets/discord_bot_token
      - LLM_API_TOKEN_FILE=/run/secrets/llm_api_token
      
    volumes:
      # Mount the local ./data directory to /app/data in the container
      # This persists the categorized_roles.json file outside the container.
      - ./data:/app/data 
      
      # Mount the local ./logs directory to /app/logs in the container
      # This persists log files outside the container if file logging is enabled.
      - ./logs:/app/logs
     # Mount the prompts directory to allow for live editing without rebuilding
      - ./prompts:/app/prompts
        
    restart: unless-stopped # Restart policy: restarts unless explicitly stopped or on error
    
    secrets:
      - discord_bot_token
      - llm_api_token

    networks:
      - intranet

networks: 
  intranet:
    external: true

# Define the secrets to be used by services
secrets:
  discord_bot_token:
    file: ./secrets/discord_token.txt # Path to your discord token secret on the host
  llm_api_token:
    file: ./secrets/llm_api_token.txt # Path to your llm api token secret on the host